### ISSUE TITLE
Add the "007: The World Is Not Enough" game in the list of game titles

### ISSUE THREAD

**Issue by KAUTH** [KAUTH/Retro-Gamez#13]
In [game_list.js](https://github.com/KAUTH/Retro-Gamez/blob/master/retro-gamez/popup/game_list.js), add another item in the game_List array with the following values:
"id": 25,
"title": "007: The World Is Not Enough",
"src": "https://www.retrogames.cc/embed/41522-007-the-world-is-not-enough.html"

For more details check out the [HACKTOBERFEST-CONTRIBUTING.md](https://github.com/KAUTH/Retro-Gamez/blob/master/HACKTOBERFEST-CONTRIBUTING.md) file.

**Comment by lancaluis** [comment]
Hey! I'm helping you with this issue. Is it ok?

**Comment by hankoj** [comment]
I have made a PR #14 for this issue but the Greeting seemed to fail. Is that on my end?

**Comment by KAUTH** [comment]
@hankoj Thanks!! I will check it out (no the greeting failing is on our side) 😉

**Comment by KAUTH** [comment]
> Hey! I'm helping you with this issue. Is it ok?

@lancaluis Thanks for the contribution! Since this issue has already been taken care of I will assign to you a similar one.
