### ISSUE TITLE
Add the "A Bug's Life" game in the list of game titles

### ISSUE THREAD

**Issue by KAUTH** [KAUTH/Retro-Gamez#16]
In [game_list.js](https://github.com/KAUTH/Retro-Gamez/blob/master/retro-gamez/popup/game_list.js), add another item in the game_List array with the following values:
"id": 26,
"title": "A Bug's Life",
"src": "https://www.retrogames.cc/embed/41523-a-bugs-life.html"

For more details check out the [HACKTOBERFEST-CONTRIBUTING.md](https://github.com/KAUTH/Retro-Gamez/blob/master/HACKTOBERFEST-CONTRIBUTING.md) file.

**Comment by syauqy** [comment]
Can I work on this?

**Comment by KAUTH** [comment]
> Can I work on this?

@syauqy Hey, thanks for contributing! Yes, I assigned it to you.

**Comment by syauqy** [comment]
Please kindly check my PR here #22 . Thanks
