### ISSUE TITLE
Add the "A-Train - Trains, Power, Money" game in the list of game titles

### ISSUE THREAD

**Issue by KAUTH** [KAUTH/Retro-Gamez#17]
In [game_list.js](https://github.com/KAUTH/Retro-Gamez/blob/master/retro-gamez/popup/game_list.js), add another item in the game_List array with the following values:
"id": 27,
"title": "A-Train - Trains, Power, Money",
"src": "https://www.retrogames.cc/embed/40096-a-train-trains-power-money.html"

For more details check out the [HACKTOBERFEST-CONTRIBUTING.md](https://github.com/KAUTH/Retro-Gamez/blob/master/HACKTOBERFEST-CONTRIBUTING.md) file.

**Comment by stanjdev** [comment]
I can add this if you want to assign me, thank you!
