### ISSUE TITLE
Add the "Ace Combat" game in the list of game titles

### ISSUE THREAD

**Issue by KAUTH** [KAUTH/Retro-Gamez#18]
In [game_list.js](https://github.com/KAUTH/Retro-Gamez/blob/master/retro-gamez/popup/game_list.js), add another item in the game_List array with the following values:
"id": 28,
"title": "Ace Combat",
"src": "https://www.retrogames.cc/embed/41524-ace-combat.html"

For more details check out the [HACKTOBERFEST-CONTRIBUTING.md](https://github.com/KAUTH/Retro-Gamez/blob/master/HACKTOBERFEST-CONTRIBUTING.md) file.

**Comment by nitish-awasthi** [comment]
I think the id should be 26? @KAUTH

**Comment by KAUTH** [comment]
> I think the id should be 26? @KAUTH

@nitish-awasthi thanks for the comment! However, there is a previous issue, with a game title to be added with the id of 26.
