### ISSUE TITLE
Create a "License" shield for the README.md

### ISSUE THREAD

**Issue by KAUTH** [KAUTH/Retro-Gamez#30]
Visit [https://shields.io/](https://shields.io/) and create a License shield for the [REAME.md](https://github.com/KAUTH/Retro-Gamez/blob/master/README.md).

**Comment by thomaslian** [comment]
Hi, I'll do this

**Comment by KAUTH** [comment]
> Hi, I'll do this

Hey @thomaslian thanks for wanting to contribute, but this issue is already assigned. Watch out for new issues with the Hacktoberfest label soon! : )

**Comment by thomaslian** [comment]
Okay, thanks:)

**Comment by KAUTH** [comment]
> Okay, thanks:)

@thomaslian Check out Issue #34 if you are still interested!
