### ISSUE TITLE
Add the "Rayman" game in the list of game titles

### ISSUE THREAD

**Issue by KAUTH** [KAUTH/Retro-Gamez#34]
In [game_list.js](https://github.com/KAUTH/Retro-Gamez/blob/master/retro-gamez/popup/game_list.js), add another item in the game_List array with the following values:
"id": 32,
"title": "Rayman",
"src": "https://www.retrogames.cc/embed/40795-rayman.html"

For more details check out the [HACKTOBERFEST-CONTRIBUTING.md](https://github.com/KAUTH/Retro-Gamez/blob/master/HACKTOBERFEST-CONTRIBUTING.md) file.

**Comment by thomaslian** [comment]
I'll do it! :)
