### ISSUE TITLE
Add 7 more game titles

### ISSUE THREAD

**Issue by KAUTH** [KAUTH/Retro-Gamez#5]
At [game_list.js](https://github.com/KAUTH/Retro-Gamez/blob/master/retro-gamez/popup/game_list.js), add 7 new items in the _gameList_ array.

Go to https://www.retrogames.cc/ and get the source link for the iframes that are given as embedded code. Select among the most popular titles first.
Add a new item in the _gameList_ array by incrementing the id number, giving the title of the game, and placing as source the source link that is mentioned above.

In the end, there will be a total of 31 different game titles available by the Retro-Gamez extension, a different one for each day of the month.

**Comment by Any28Flo** [comment]
I could help with this if  you want. At hacktoberfest

**Comment by KAUTH** [comment]
Thanks! Actually I am preparing a CONTRIBUTING.md and some issues, like the above one, just for Hacktoberfest.
So if you want to, you can follow the project and in the beginning of October, when I will have everything ready, you will get a notification on GitHub 😉.
