### ISSUE TITLE
 Add the "FIFA 2000" game in the list of game titles

### ISSUE THREAD

**Issue by KAUTH** [KAUTH/Retro-Gamez#59]
In [game_list.json](https://github.com/KAUTH/Retro-Gamez/blob/master/retro-gamez/popup/game_list.json), add another item in the array with the following values:
"id": 35,
"title": "FIFA 2000",
"src": "https://www.retrogames.cc/embed/41776-fifa-2000.html"

For more details check out the [HACKTOBERFEST-CONTRIBUTING.md](https://github.com/KAUTH/Retro-Gamez/blob/master/HACKTOBERFEST-CONTRIBUTING.md) file.

**Comment by rsk2** [comment]
Hi @KAUTH, can I work on this?

**Comment by KAUTH** [comment]
Hey, @rsk2 welcome to the project! Thanks, I will assign this to you

**Comment by rsk2** [comment]
> Hey, @rsk2 welcome to the project! Thanks, I will assign this to you

Thanks!
