### ISSUE TITLE
Host game list file online

### ISSUE THREAD

**Issue by KAUTH** [KAUTH/Retro-Gamez#7]
In order to avoid updating the Firefox extension every time we want to add a new game title to the list of available games, it is better to **host the game_list.js file online** and not locally. [Another option would be to create an API online.]

We can do that either on an online hosting service or more preferably on Github's raw content viewer (e.g., https://raw.githubusercontent.com/KAUTH/Retro-Gamez/master/retro-gamez/popup/game_list.js?).

In both cases, it is important to include the [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) header in the host server's response to the browser.

In Github, it supposedly returns a CORS header automatically (needs to be checked).
On an Apache-like server we need to add the following code in the _.htaccess_ file:
`Header set Access-Control-Allow-Origin "*"`

**Comment by paulopacitti** [comment]
I think a better way to do this is to convert `game_list.js` in `game_list.json`. Then, obtain the content of this file fetching with GET at https://raw.githubusercontent.com/KAUTH/Retro-Gamez/master/retro-gamez/popup/game_list.json anf parse it in the `retro_gamez.js`. What do you think? I'd be happy to help with this issue :)

**Comment by KAUTH** [comment]
Hey @paulopacitti thanks for the advice! Yes, if you would like to help that would be great. 
I've already tried what you suggested. When running it locally it works fine. However, I have a "cross origin request" problem when testing it as a Firefox add-on (I can send you a link for Firefox add-on debugging documentation).

**Comment by paulopacitti** [comment]
Hmmm, I see it 😕  I'll try to bypass it somehow, that's got be a way to do this hahahaha Could you assign me for this issue? ✨
